//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAgriculture
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBagricultureEntities : DbContext
    {
        public DBagricultureEntities()
            : base("name=DBagricultureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<engrai> engrais { get; set; }
        public DbSet<Irrigation> Irrigations { get; set; }
        public DbSet<Pesticide> Pesticides { get; set; }
        public DbSet<prix> prixes { get; set; }
    }
}
