//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAgriculture
{
    using System;
    using System.Collections.Generic;
    
    public partial class prix
    {
        public int id { get; set; }
        public string NomEquip { get; set; }
        public Nullable<int> Prix1 { get; set; }
    }
}
